require:
  rubocop-rails


Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false